// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0b0onnud7VB8HZ-jL4WldQSYQ3H0QCrQ',
    appId: '1:747951208672:web:44a617808e1101529ff885',
    messagingSenderId: '747951208672',
    projectId: 'ecommerce-app-00101101',
    authDomain: 'ecommerce-app-00101101.firebaseapp.com',
    storageBucket: 'ecommerce-app-00101101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB0q-2VirtdzPInltN27osGAX2K4JZfsM',
    appId: '1:747951208672:android:55650ef19a9132d59ff885',
    messagingSenderId: '747951208672',
    projectId: 'ecommerce-app-00101101',
    storageBucket: 'ecommerce-app-00101101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCH2f4TfA6vgG2nDPGgp-Xo6WMnK64AKk',
    appId: '1:747951208672:ios:aa164100381f8eeb9ff885',
    messagingSenderId: '747951208672',
    projectId: 'ecommerce-app-00101101',
    storageBucket: 'ecommerce-app-00101101.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCH2f4TfA6vgG2nDPGgp-Xo6WMnK64AKk',
    appId: '1:747951208672:ios:aa164100381f8eeb9ff885',
    messagingSenderId: '747951208672',
    projectId: 'ecommerce-app-00101101',
    storageBucket: 'ecommerce-app-00101101.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0b0onnud7VB8HZ-jL4WldQSYQ3H0QCrQ',
    appId: '1:747951208672:web:0abb3e17f47fb4e69ff885',
    messagingSenderId: '747951208672',
    projectId: 'ecommerce-app-00101101',
    authDomain: 'ecommerce-app-00101101.firebaseapp.com',
    storageBucket: 'ecommerce-app-00101101.firebasestorage.app',
  );
}
